name: Discord Issue Notifier

on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send issue update to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ACTION="${{ github.event.action }}"
          TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/"/\\"/g')
          URL="${{ github.event.issue.html_url }}"
          AUTHOR="${{ github.event.issue.user.login }}"
          TIMESTAMP="${{ github.event.issue.updated_at }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"üêõ Issue $ACTION\",
            \"embeds\": [{
              \"title\": \"$TITLE\",
              \"url\": \"$URL\",
              \"timestamp\": \"$TIMESTAMP\",
              \"color\": 15105570,
              \"description\": \"**Author:** [$AUTHOR](https://github.com/$AUTHOR)\"
            }]
          }" \
          $DISCORD_WEBHOOK_URL